export const services = [
  {
    num: '01',
    title: 'Data Analytics\n& Business Intelligence',
    desc: 'Transformamos dados brutos em insights accionáveis através de dashboards avançados e análise estatística rigorosa para suporte à decisão.',
    tags: ['Power BI', 'Python', 'SQL', 'ETL', 'Dashboards'],
    featured: false,
    icon: 'code',
  },
  {
    num: '02',
    title: 'Sistemas de\nInteligência Artificial',
    desc: 'Desenvolvimento de agentes inteligentes, modelos preditivos e integração de LLMs para automação e optimização de processos complexos.',
    tags: ['Machine Learning', 'RAG', 'Prompt Engineering', 'LLMs'],
    featured: true,
    icon: 'ai',
  },
  {
    num: '03',
    title: 'Geotecnologias\n& GIS (SIG)',
    desc: 'Análise espacial de alta precisão, monitoramento remoto e cartografia interactiva para planeamento territorial e mitigação de riscos.',
    tags: ['QGIS', 'ArcGIS', 'Remote Sensing', 'Spatial Analysis'],
    featured: true,
    icon: 'map',
  },
  {
    num: '04',
    title: 'Monitoramento & Alerta\nSentinel System',
    desc: 'Sistemas de vigilância de dados em tempo real para segurança, monitoramento ambiental e resposta humanitária rápida.',
    tags: ['Real-time', 'Alerts', 'Monitoring', 'Surveillance'],
    featured: false,
    icon: 'grid',
  },
  {
    num: '05',
    title: 'Estratégia de Dados\nImpacto Humanitário',
    desc: 'Consultoria técnica para ONGs e Governo em digitalização de MEAL e frameworks de dados para desenvolvimento sustentável.',
    tags: ['MEAL', 'Humanitarian', 'Strategy', 'Auditoria'],
    featured: false,
    icon: 'info',
  },
  {
    num: '06',
    title: 'Capacitação Técnica\nEspecializada',
    desc: 'Treinamento em ferramentas de ponta: Python para dados, GIS aplicado e IA Generativa para equipas de alta performance.',
    tags: ['Formação', 'Workshops', 'Data Literacy'],
    featured: false,
    icon: 'book',
  },
]

export const projects = [
  {
    id: 'xlsform-ai',
    title: 'XLSForm AI Translator para Microsoft Excel',
    category: 'IA & Automação',
    desc: 'Suplemento de Excel para traduzir formulários Kobo/XLSForm e intervalos seleccionados, preservando variáveis, fórmulas, placeholders, formatação e lógica do questionário.',
    link: 'https://github.com/Jubilio/xlsform-ai-translator',
    image: 'https://image.thum.io/get/width/1366/crop/768/noanimate/https://xlsform-ai-translator.onrender.com/taskpane.html',
    tags: ['Office.js', 'XLSForm', 'LLMs'],
  },
  {
    id: 'gpx-converter',
    title: 'GPX Batch Converter para QGIS',
    category: 'GIS & Automação',
    desc: 'Ferramenta para conversão em lote de centenas de ficheiros GPX em Shapefile, com normalização de nomes, relatórios de execução, controlo de erros e compatibilidade preparada para QGIS 3 e 4.',
    link: 'https://github.com/Jubilio/gpx-batch-converter',
    image: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&q=80&w=1200',
    tags: ['QGIS', 'Python', 'GPX'],
  },
  {
    id: 'groundwater-mueda',
    title: 'Mapeamento do Potencial de Águas Subterrâneas — Mueda',
    category: 'Investigação GIS & RS',
    desc: 'Estudo científico que integra sensoriamento remoto, AHP em SIG e validação com fontes de água para identificar zonas com potencial de águas subterrâneas no norte de Moçambique.',
    link: 'https://data.mendeley.com/drafts/8n7m7pwrp9',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=1200',
    tags: ['AHP', 'Earth Engine', 'Groundwater'],
  },
  {
    id: 'humanitarian-risk',
    title: 'Análise de Risco Humanitário e Necessidades Agudas',
    category: 'Humanitarian Data',
    desc: 'Framework analítico para triangular segurança alimentar, WASH, saúde e condições de vida, apoiando a identificação de populações e áreas com maior risco de necessidades críticas.',
    link: 'mailto:jubilio@nexovibe.co.mz?subject=Análise%20de%20Risco%20Humanitário',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=1200',
    tags: ['Risk Analytics', 'MEAL', 'GIS'],
  },
  {
    id: 'sentinel',
    title: 'Sentinel — Intelligent Monitoring Platform',
    category: 'AI & Security',
    desc: 'Sistema avançado de monitoramento e autenticação segura, servindo como base para infraestruturas de alerta e acompanhamento em tempo real.',
    link: 'https://sentinel-seven-rosy.vercel.app/',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=1200',
    tags: ['Auth', 'Real-time', 'Monitoring'],
  },
  {
    id: 'discovery',
    title: 'AI-Powered Content Discovery Platform',
    category: 'IA & Data',
    desc: 'Plataforma de gestão de conhecimento que utiliza classificação inteligente de dados para optimizar a descoberta e organização de informação digital.',
    link: 'https://leitorlivros.netlify.app/',
    image: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&q=80&w=1200',
    tags: ['Library', 'IA', 'Categorization'],
  },
  {
    id: 'mwanga',
    title: 'Smart Link Intelligence Dashboard',
    category: 'Data Analytics',
    desc: 'Ecossistema de gestão de links com analytics integrado para rastreamento de desempenho e centralização estratégica de activos digitais.',
    link: 'https://mwanga-opal.vercel.app/',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1200',
    tags: ['Analytics', 'Management', 'Dashboard'],
  },
  {
    id: 'waterwatch',
    title: 'WaterWatch — WebGIS de Consumo de Água',
    category: 'WebGIS',
    desc: 'Aplicação WebGIS para exploração espacial do consumo de água, combinando visualização cartográfica interactiva e indicadores para análise territorial.',
    link: 'https://github.com/Jubilio/WaterWatch',
    image: 'https://images.unsplash.com/photo-1538300342682-cf57afb97285?auto=format&fit=crop&q=80&w=1200',
    tags: ['Leaflet', 'WebGIS', 'Water'],
  },
]

export const stats = [
  { num: '5+', label: 'Anos de Experiência' },
  { num: '25+', label: 'Soluções & Automações' },
  { num: '15+', label: 'Projectos GIS & Dados' },
  { num: '100%', label: 'Orientação a Impacto' },
]

export const tools = [
  'Python','R','QGIS','ArcGIS','JavaScript','TypeScript',
  'Next.js','PostgreSQL','PostGIS','Supabase','Claude AI',
  'OpenAI API','Power BI','Tableau','Pandas','Geopandas',
  'Earth Engine','Docker','Git','Tailwind CSS','Office.js',
  'KoboToolbox','XLSForm',
]

export const steps = [
  {
    num: '01',
    title: 'Análise Dialéctica',
    desc: 'Mergulho profundo nos seus problemas de dados para identificar as raízes da ineficiência estratégica.',
    icon: 'chat',
  },
  {
    num: '02',
    title: 'Arquitectura',
    desc: 'Desenho de soluções que integram IA, Espaço e Dados de forma harmoniosa e escalável.',
    icon: 'doc',
  },
  {
    num: '03',
    title: 'Deploy Inteligente',
    desc: 'Implementação ágil com foco em segurança de dados e facilidade de decisão para os utilizadores.',
    icon: 'pulse',
  },
  {
    num: '04',
    title: 'Impacto & Escala',
    desc: 'Acompanhamento contínuo para garantir que a solução evolui com os desafios do mercado moçambicano.',
    icon: 'check',
  },
]
