import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
export const metadata: Metadata = {title:"Relatório demonstrativo de segurança",description:"Exemplo fictício de entrega: âmbito, evidências, recomendações e reteste de uma aplicação de IA."};
export default function SampleReport(){return <><Navbar/><main id="main-content" className="container report-page">
<p className="eyebrow">NEXOVIBE / EXEMPLO DE ENTREGA</p><h1>Da evidência à correcção.</h1>
<p className="report-notice"><strong>Relatório demonstrativo · Cenário fictício.</strong> Este exemplo ilustra a estrutura de uma entrega. Não documenta um teste real, um cliente ou uma certificação.</p>
<dl className="report-facts"><div><dt>Sistema ilustrativo</dt><dd>Assistente interno com pesquisa documental (RAG)</dd></div><div><dt>Tipo de avaliação</dt><dd>Revisão de controlo de acesso a documentos</dd></div><div><dt>Referência</dt><dd>DEMO-01</dd></div><div><dt>Estado</dt><dd>Exemplo fictício, sem validação em ambiente real</dd></div></dl>
<section><h2>01 / Resumo executivo</h2><p>Neste cenário, um utilizador de uma equipa obtém um excerto de um documento reservado a outra equipa. A falha está na autorização durante a pesquisa documental e pode expor informação interna. A prioridade proposta é corrigir o controlo de acesso antes de alargar a utilização do assistente.</p></section>
<section><h2>02 / Âmbito e limitações</h2><p>Ambiente de teste, dois perfis de utilizador e documentos sintéticos de duas equipas. Inclui pesquisa, recuperação de excertos e resposta do assistente. Exclui infraestrutura, outros sistemas e dados de produção. Numa avaliação real, os activos, autorizações e limites são definidos antes dos testes.</p></section>
<section><h2>03 / Resultado demonstrativo</h2><h3>Pesquisa documental sem filtro de autorização</h3><dl className="report-facts"><div><dt>Severidade ilustrativa</dt><dd>Alta, sujeita ao impacto e contexto reais</dd></div><div><dt>Condição</dt><dd>Conta autenticada com acesso limitado à equipa A</dd></div></dl><p><strong>Comportamento esperado:</strong> o utilizador recebe apenas informação de documentos para os quais tem permissão.</p><p><strong>Comportamento observado no cenário:</strong> a resposta inclui um marcador sintético de um documento da equipa B, indisponível na interface documental do utilizador.</p><ol><li>Criar um documento sintético exclusivo da equipa B com um marcador de teste.</li><li>Iniciar sessão com o perfil da equipa A e efectuar uma pesquisa relacionada.</li><li>Comparar as fontes recuperadas e a resposta com as permissões do perfil.</li><li>Guardar o pedido, a resposta e os identificadores sintéticos, sem dados sensíveis.</li></ol><p><strong>Evidência ilustrativa:</strong> perfil A → pesquisa → excerto com o marcador DEMO-EQUIPA-B. Num relatório real, anexar evidências expurgadas, data, versão do sistema e condições de reprodução.</p></section>
<section><h2>04 / Recomendações</h2><ul><li>Aplicar autorização no servidor antes de disponibilizar documentos ou excertos ao modelo.</li><li>Usar a identidade e as permissões da sessão validada, sem confiar em identificadores enviados pelo utilizador.</li><li>Rever o isolamento de índices, caches e fontes citadas.</li><li>Adicionar verificações de acesso entre equipas e registar tentativas recusadas sem armazenar conteúdo sensível desnecessário.</li></ul></section>
<section><h2>05 / Critérios de reteste</h2><p>Repetir os testes com ambos os perfis após a correcção. Confirmar que a equipa A não recebe excertos, citações ou respostas derivadas dos documentos da equipa B e que o acesso legítimo continua a funcionar. Documentar o estado como corrigido, parcialmente corrigido, não corrigido ou não retestado, com as respectivas evidências.</p></section>
<section><h2>06 / Próximas acções</h2><p>Na entrega real, cada acção deve ter prioridade, responsável e prazo acordados. O reteste confirma apenas as correcções verificadas no âmbito definido; não constitui garantia de ausência de outras falhas.</p><div className="button-row"><Link href="/#contacto" className="button button-primary">Conversar sobre uma avaliação ↗</Link><Link href="/#entregaveis" className="button button-quiet">Voltar aos entregáveis</Link></div></section>
</main><Footer/></>}
