// Build-time localisation keeps both languages static and shares the Portuguese
// component templates. Update locales/en.json; do not edit generated output.
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
const root = process.cwd();
const catalog = JSON.parse(fs.readFileSync('locales/en.json', 'utf8'));
for (const output of ['src/app/en', 'src/generated/en']) fs.rmSync(output, { recursive: true, force: true });
const norm = value => value.replace(/\s+/g, ' ').trim();
const routes = ['sobre', 'portfolio', 'convites', 'privacidade', 'relatorio-exemplo', 'xlsform-translator', 'scanner'];
function route(value) {
  if (value === '/') return '/en';
  if (value.startsWith('/#') || routes.some(p => value === `/${p}` || value.startsWith(`/${p}/`) || value.startsWith(`/${p}#`))) return '/en' + value;
  if (value.startsWith('https://nexovibe.netlify.app')) return 'https://nexovibe.netlify.app' + route(value.slice(28) || '/');
  return value;
}
const sourceFiles = [];
function walk(dir) { for (const entry of fs.readdirSync(dir, {withFileTypes:true})) { const file = path.join(dir, entry.name); if(entry.isDirectory()) walk(file); else if(/\.tsx?$/.test(file)) sourceFiles.push(file); } }
walk('src/components'); walk('src/app/(pt)');
sourceFiles.push('src/lib/data.ts','src/lib/case-studies.ts','src/lib/invitations.ts','src/lib/contact.ts');
const strings = new Set();
for (const source of sourceFiles) {
  if(source.endsWith('/LanguageSwitcher.tsx')) continue;
  const code = fs.readFileSync(source,'utf8');
  const ast = ts.createSourceFile(source,code,ts.ScriptTarget.Latest,true,source.endsWith('tsx')?ts.ScriptKind.TSX:ts.ScriptKind.TS);
  const edits=[];
  function visit(node) {
    const isText=ts.isJsxText(node);
    const isLiteral=ts.isStringLiteral(node)||ts.isNoSubstitutionTemplateLiteral(node);
    const isPart=[ts.SyntaxKind.TemplateHead,ts.SyntaxKind.TemplateMiddle,ts.SyntaxKind.TemplateTail].includes(node.kind);
    if(isText||isLiteral||isPart) {
      const value=node.text, key=norm(value);
      if(key && !source.includes('/xlsform-translator/') && !source.endsWith('XLSFormLegalPage.tsx')) strings.add(key);
      let translated=catalog[key]??value;
      if(isLiteral||isPart) translated=route(translated);
      if(isLiteral && value.startsWith('@/components/') && !value.endsWith('/LanguageSwitcher')) translated=value.replace('@/components/','@/generated/en/components/');
      if(isLiteral && ['@/lib/data','@/lib/case-studies','@/lib/invitations','@/lib/contact'].includes(value)) translated=value.replace('@/lib/','@/generated/en/lib/');
      if(value==='./LanguageSwitcher') translated='@/components/ui/LanguageSwitcher';
      if(value==='./convites.module.css') translated='@/app/(pt)/convites/convites.module.css';
      if(value==='../globals.css') translated='@/app/globals.css';
      if(value==='pt-MZ') translated='en';
      if(value==='pt_MZ') translated='en_GB';
      // metadataBase is an origin, not a navigable page URL.
      if(ts.isNewExpression(node.parent) && node.parent.expression.getText(ast)==='URL') translated=value;
      if(translated!==value) {
        let replacement;
        if(isText) replacement=' '+translated+' ';
        else if(isPart) {
          const spacing = catalog[key] !== undefined ? (value.match(/^\s*/)?.[0] || '') + translated + (value.match(/\s*$/)?.[0] || '') : translated;
          replacement=(node.kind===ts.SyntaxKind.TemplateHead?'`':'}')+spacing.replace(/`/g,'\\`')+(node.kind===ts.SyntaxKind.TemplateTail?'`':'${');
        }
        else replacement=JSON.stringify(translated);
        edits.push({start:isText?node.pos:node.getStart(ast),end:node.end,replacement});
      }
    }
    ts.forEachChild(node,visit);
  }
  visit(ast);
  let output=code;
  for(const edit of edits.sort((a,b)=>b.start-a.start)) output=output.slice(0,edit.start)+edit.replacement+output.slice(edit.end);
  if(source.endsWith('/ContactForm.tsx')) output=output.replace('typeof result?.error === "string" ? result.error : ', '');
  if(source.endsWith('/XLSFormLegalPage.tsx')) output=fs.readFileSync('locales/XLSFormLegalPage.en.tsx','utf8');
  const destination=source.startsWith('src/app/(pt)/')?source.replace('src/app/(pt)/','src/app/en/'):source.replace('src/','src/generated/en/');
  fs.mkdirSync(path.dirname(destination),{recursive:true});fs.writeFileSync(destination,'// Generated by scripts/build-locales.mjs.\n'+output);
}
if(process.argv.includes('--extract')) fs.writeFileSync('/tmp/nexovibe-locale-strings.json',JSON.stringify([...strings].sort(),null,2));
console.log(`English routes generated from ${sourceFiles.length} shared source files.`);
