import type { Metadata } from "next";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
export const metadata: Metadata = { title: "Privacidade e contacto", alternates: { canonical: "/privacidade" } };
export default function PrivacyPage() {
  return <><Navbar /><main id="main-content" className="container report-page">
    <p className="eyebrow">NEXOVIBE / PRIVACIDADE</p><h1>Os dados do seu contacto.</h1>
    <p>Esta página explica o tratamento dos dados no site institucional da NexoVibe e nos pedidos de proposta. Actualizada em 9 de Outubro de 2026.</p>
    <section><h2>Quem recebe o pedido</h2><p>O contacto comercial é gerido pela NexoVibe, sob responsabilidade de Jubílio Maússe, em Moçambique. Para questões sobre os seus dados, escreva para <a className="text-link" href="mailto:nexovibecontact@gmail.com">nexovibecontact@gmail.com</a>.</p></section>
    <section><h2>Informação recolhida e finalidade</h2><p>O formulário recolhe o nome, email, serviço e mensagem. Pode incluir voluntariamente informações sobre o projecto, evento, prazo ou orçamento. Utilizamos estes dados para responder, esclarecer requisitos e preparar a proposta. O envio não subscreve uma newsletter.</p><p>Não envie palavras-passe, chaves de API, listas de convidados, dados de beneficiários ou outros dados sensíveis no primeiro contacto.</p></section>
    <section><h2>Serviços envolvidos</h2><p>A Netlify aloja o site e processa os pedidos. A Brevo encaminha a mensagem para a caixa de correio da NexoVibe no Gmail, operado pela Google. Estes fornecedores podem tratar informação técnica e dados fora de Moçambique, segundo as suas políticas e condições.</p><p>O endereço IP pode ser utilizado pela infraestrutura de alojamento para registos técnicos e limitação de pedidos. O código do formulário não regista o conteúdo da mensagem nem a chave do serviço de email nos logs.</p></section>
    <section><h2>Conservação e pedidos sobre os dados</h2><p>O formulário não mantém uma base de dados própria de contactos. As mensagens enviadas permanecem nos serviços de email até serem eliminadas; os registos técnicos seguem as configurações dos fornecedores. Pode solicitar acesso, correcção ou eliminação pelo email acima. Eventuais necessidades de conservação relacionadas com uma prestação de serviços serão esclarecidas na resposta.</p></section>
    <section><h2>Navegação e serviços externos</h2><p>O site institucional não incorpora ferramentas de publicidade ou análise de audiência no seu código. Os links para GitHub, QGIS e outros serviços levam a sites com políticas próprias. As preferências e registos técnicos da infraestrutura são geridos pelos respectivos fornecedores.</p></section>
    <section><h2>Scanner e XLSForm Translator</h2><p>O AI Scanner permite testes locais simulados e pedidos do navegador ao endpoint HTTPS indicado pelo utilizador. Em modo real, esse endpoint recebe os pedidos e a chave que o utilizador introduzir. As avaliações permanecem na sessão do navegador e podem ser exportadas; reveja o conteúdo antes de partilhar.</p><p>O XLSForm AI Translator tem uma <a className="text-link" href="/xlsform-translator/privacy">política de privacidade específica</a>.</p></section>
  </main><Footer /></>;
}
